server:
  port: 8002
spring:
  devtools:
    restart:
      enabled: true
      exclude: application.yml,static/**,public/**

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志