
### 登录测试
POST http://localhost:8090/api/business/admin/login
Content-Type: application/json;charset=utf-8

{
  "mobile": "16607211503",
  "password": "zzb200166"
}

> {%
    client.global.set("token",response.body.data.token)
%}

### 查询注册
GET http://localhost:8090/api/business/daily_train_carriage/query_list?page=1&size=10
Accept: application/json
token:{{token}}
