server:
  port: 8003
spring:
  application:
    name: batch
  devtools:
    restart:
      enabled: true
      exclude: application.yml,static/**,public/**
  datasource:
    url: jdbc:mysql://localhost:3306/train_batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    password: zzb200166
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler.instanceName: MyClusteredScheduler
      org.quartz.scheduler.instanceId: test
      org.quartz.jobStore.isClustered: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
