### 测试注册
POST http://localhost:8090/api/business/train/save
Content-Type: application/json;charset=utf-8

{
  "mobile": "16607211504",
  "password": "zzb200166"
}

### 查询
GET http://localhost:8090/api/business/train/query_list?page=1&size=10
Accept: application/json
token:{{token}}

### 查询注册
GET http://localhost:8090/api/business/train/query_all
Accept: application/json
token:{{token}}

###自动生成座位测试
GET http://localhost:8090/api/business/train/gen/G1
Accept: application/json
token:{{token}}