### 测试注册
POST http://localhost:8090/api/business/train_station/save
Content-Type: application/json;charset=utf-8

{
  "mobile": "16607211504",
  "password": "zzb200166"
}

### 查询
GET http://localhost:8090/api/business/train_station/query_list?page=1&size=10&trainCode=G2
Accept: application/json
token:{{token}}
